version: "3.8"
networks:
  cassandra:
services:
  cass1:
    image: cassandra:latest
    container_name: cass1
    hostname: cass1
    mem_limit: 2g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data/cass1:/var/lib/cassandra
      - ./etc/cass1:/etc/cassandra
      - ./scripts:/scripts

    environment: &environment
      CASSANDRA_SEEDS: "cass1,cass2"
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: West
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128

  cass2:
    image: cassandra:latest
    container_name: cass2
    hostname: cass2
    mem_limit: 2g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - ./data/cass2:/var/lib/cassandra
      - ./etc/cass2:/etc/cassandra
      - ./scripts:/scripts
    environment:
      <<: *environment
    depends_on:
      cass1:
        condition: service_healthy
  cass3:
    image: cassandra:latest
    container_name: cass3
    hostname: cass3
    mem_limit: 2g
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - cassandra
    ports:
      - "9045:9042"
    volumes:
      - ./data/cass3:/var/lib/cassandra
      - ./etc/cass3:/etc/cassandra
      - ./scripts:/scripts
    environment:
      <<: *environment
    depends_on:
      cass2:
        condition: service_healthy
